import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./components/navbar/navbar";
import "./globals.css";
import Banner from "./components/banner/banner";
import BrandList from "./components/brandlist/brandlist";

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Super Maintenance Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <title>Super Maintenance Website</title>
      {/* <Link src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet" /> */}
    </head>
      <body>
        <Navbar/>
        <Banner/>
        <BrandList/>
        {children}
      </body>
    </html>
  );
}
